services:
  - type: web
    name: my-notify-trading-bot-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    healthCheckPath: /health
